### ISSUE TITLE
Hi, I'm getting error in the line 554

### ISSUE THREAD

**Issue by PabloArty** [terrymun/paver#10]
The error is in this line
paver.$t.on('mousemove.paver', $.throttle(paver.settings.cursorThrottle, function(e){

I already load the paver css and js. 

I'm using jquery v3.1.0

**Comment by terrymun** [comment]
Paver has been thoroughly tested with jQuery v3.1.1 (the latest commit, d13b8ef, uses jQuery v3.1.1 for all demo pages). It seems like you have forgotten to load Ben Alman's [$.throttle plugin](http://benalman.com/projects/jquery-throttle-debounce-plugin/).

**Comment by PabloArty** [comment]
So yes! haha thanks all is working good now. cheers!

2016-09-30 19:40 GMT+02:00 Terry Mun notifications@github.com:
