### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by calraiden** [terrymun/paver#15]
What's name to install by bower?

```
$ bower install paver --save
bower                        ENOTFOUND Package paver not found
```

**Comment by terrymun** [comment]
Thanks for highlighting that! I forgot to submit Paver to bower in the haste of publishing. It is now available via both NPM (as a scoped package, `@terrymun/paver`) on on bower (`bower`):

```bash
# Install using npm
$ npm install @terrymun/paver

# Install using bower
$ bower install paver
```
