### ISSUE TITLE
Paver in Slideshow freezes on mobile

### ISSUE THREAD

**Issue by TheNewGuy16** [terrymun/paver#16]
Hey awesome code and really cool feature to use. Trying to use it in a dynamic portfolio plugin, where the admin can add portfolio pieces and thumbnails in wordpress and i pull it to the front end through a loop. I only want the paver on mobile devices.  The images are fine on desktop since they usually fit in the screen.  So for mobile phones I am trying to use paver with in a flickity slideshow.  But sometimes the paver freezes and i cant figure out why or how to make it work better as of now I just destroy all pavers then use a conditional statement and find the pano-wrapper that has a class of is-selected and then initialize paver again once the slide has settled.  It works ok but there is the fade in when the paver is intialized.  If i dont destroy the paver and just intialize all tha pano-wrappers so that its ready to go when you swipe to the next slide that works ok and there is no fade in but sometimes the paver freezes after switching slides a couple of times so i am just wondering if you have any ideas on what we could do to get this to work better. 

you can check out the feature here avidbeta.com/portfolio/ and click into the first portfolio.  

thanks you for any help you can offer.

**Comment by terrymun** [comment]
I can't really understand your issue. Perhaps you can rephrase it? I checked out the portfolio on my iOS device, and Paver seems to be working just fine, so I can't really figure out the issue you are describing.

Also, I'm not sure what "fade in" are you talking about—Paver doesn't have this feature implemented at all.

**Comment by TheNewGuy16** [comment]
did you see the fade in that happens when you swipe to another slide?  is there a way to soften that. so it doesnt look so glitchy

**Comment by terrymun** [comment]
I don't see any fade in. All I see is the image being position to the left, and then it gets repositioned to the center. Is that the "fade in" you are talking about?

**Comment by TheNewGuy16** [comment]
yes....is there away to make that work better....

**Comment by terrymun** [comment]
You might want to look at preloading the image after each slide transition, and hide the paver element until it is fully initialised.

**Comment by TheNewGuy16** [comment]
hmm ok so there is a settle function for flickity.js and that is what i am using once the slide is settled then it initializes the paver but that is when we are seeing the centering of the slide.  So any ideas on how i can get around that....

**Comment by TheNewGuy16** [comment]
so in my original question if i just initialize all of my pano-wrappers with paver then that helps the feel of the slideshow and it doesn't have the weird recenter but then sometimes paver get hung up.  are you available for a minute? i can revert my code to do that and you can maybe see what i am talking about

**Comment by terrymun** [comment]
As I have already said, you will have to hide the element somehow (like `visibility: hidden`?), and show it after paver is initialised after each slide transition (by listening to the [`ready.paver` event](http://terrymun.github.io/paver/demo/custom-triggers-events.html#custom-events__ready-paver)). The details of how this is implemented is up to you, but paver fires a host of events that can help you track stages of initialisation.

It's best if you can provide the two alternatives side by side, like in a JSfiddle or something slightly permanent. As paver (and all my other projects) are released on an as-is basis I do not guarantee 24/7 support.

**Comment by TheNewGuy16** [comment]
ok cool thanks for the suggestions
