### ISSUE TITLE
start position 0 is not working on android

### ISSUE THREAD

**Issue by AlaaElZein** [terrymun/paver#24]
Hello,
in the jquery.paver.js file we have changed the startPosition value to 0.
And also in the main page of out project where we have the paver we initialise it as following:
$(function () {
                // Paver
                $('div[data-paver]').paver({
                    startPosition: '0',
                   // tilt: false
                });
            });

And also in the div of the paver we have add the following: 
   <div data-paver data-start-position="0" >

and even when we test our code on mobile, the paver is not starting from the beginning of the image. how can we solve it?

**Comment by terrymun** [comment]
See http://terrymun.github.io/paver/demo/usage-notes.html#config__start-position. The config is ignored when gyroscopic data is available. 

If you want to implement it, you will probably have to make small changes to the gyroscope logic to accept that argument.
