### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ghost** [terrymun/paver#26]
Hi,

Just spent quite some time trying to understand why Paver was not rendering anymore on a fresh and clean Chrome (66.0.3359.139). Looks like your last release 1.3.3 isn't actually containing your last fixes. Would be cool to create the 1.3.4 release just to get a new working cdn version + a new github release here for those thinking "stable" versions of your script are the official releases.

**Comment by terrymun** [comment]
Thanks for the heads up! Looks like I've drafted v1.3.4 but it never got out :) thanks for the nudge.

I'm running into some build failures with Travis CI, I'll have a look at it before I release v.1.3.4 officially.

**Comment by terrymun** [comment]
@kvinlambert Thanks for the patience. I've resolved the issue with NPM (in the end updates all packages anyway), and v1.3.4 is officially released: https://github.com/terrymun/paver/releases/tag/v1.3.4

**Comment by ghost** [comment]
Thanks @terrymun for the quick fix! ;)
