### ISSUE TITLE
Auto Scroll at start

### ISSUE THREAD

**Issue by aaronhb** [terrymun/paver#5]
Is there a way to auto scroll at load to have it scroll back and forth at set speed or a click action to make a play button to make it do it?

**Comment by aaronhb** [comment]
Anyone?

**Comment by terrymun** [comment]
Simply use a `setInterval` function to call the `.pan()` method, that should work fine. See how to use `.pan()` [here](http://terrymun.github.io/paver/demo/custom-triggers-events.html#custom-trigger__pan-paver).
