### ISSUE TITLE
Mobile demo

### ISSUE THREAD

**Issue by charlesravndal** [terrymun/paver#6]
Hi! Fantastic plugin! I'm just wondering if you have a demo that works on mobile? It seems the deviceorientation doesn't work in all of the examples/demos found in your page. Also, how do you add a background on the class paver-pano cause I tried on CSS and on HTML but it didn't work out. 

Here's is the link for the test I made (I still don't get it regarding the deviceorientation not working): http://bt.kreateam.io/demo/pan/

Hope you can help and thank you!

(Btw, I also checked the one on Verge and it works on mobile platforms, but I'm still none the wiser :()

**Comment by terrymun** [comment]
I actually haven't checked on mobile yet, but I will get back to you when I get around debugging it.

**Comment by terrymun** [comment]
Alright, it seems like the issue arising is because of an incorrect merging of configuration. This has been fixed in 5147516 ;)

**Comment by charlesravndal** [comment]
It's working without problems now. Thank you very much!!!
