### ISSUE TITLE
Panorama on mobile is aligned left even with startPosition: 0.5

### ISSUE THREAD

**Issue by user928** [terrymun/paver#9]
Hello panorama image is aligned to left edge of screen on mobile devices (chrome android, safari ios) even when I use: startPosition: 0.5 ? On desktop computers is working fine.

**Comment by terrymun** [comment]
The issue you are facing is two-fold: (1) the deviceOrientation event listening is bonked in a recent demo, but has been fixed as of 5147516, and (2) [as per documentation](http://terrymun.github.io/paver/demo/usage-notes.html#config__start-position), when deviceOrientation is being listened on, the `startPosition` option will be ignored: "_This option will be nullified when gyroscopic data is in use._"
